package oops.exceptionHandling;

public class catchException {
    public static void main(String[] args) {
        fun1();
    }
    static void fun1(){
        int a=5,b=0;
        int c=a/b;
        System.out.println(c);
    }
}
